### ISSUE TITLE
Add url to this repo and/or discuss.ipfs.io so that people know where to post questions

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/proto.school#45] opened 2018-08-04 03:53 UTC
https://proto.school/ currently has no pointer to any of our IPFS channels, making it hard for folks to know where to ask questions.

**Comment by mikeal** [comment] 2018-08-06 17:08
related (possibly duplicate of) #42

**Comment by terichadbourne** [comment] 2018-10-01 16:18
What's the best URL to link to? Both of these issues (this one and #42) reference both GH and and discuss.ipfs.io - should they both listed (with an explanation of what inquiries go where) or just one?

**Comment by mikeal** [comment] 2018-10-01 17:28
For now, I expect that most of the issues with the tutorials will actually be with the tutorials themselves, so let's just link to this repo **for now.**

In the future we may want to link into a more general discussion repo or to the IPFS discuss. One concern I have with the IPFS discuss is that the moderation settings aren't super friendly to new people and proto school is scoped a little bit broader than IPFS.

**Comment by terichadbourne** [comment] 2018-10-01 20:09
Okay, I'll plan to add a link to https://github.com/ipfs-shipyard/proto.school/issues in a spot that's visible regardless of which specific tutorial you're working your way through.

**Comment by terichadbourne** [comment] 2018-10-29 15:54
Closed by merging of PR #63

**Closed by terichadbourne** 2018-10-29 15:54 UTC
